insert into exercises (name, muscle_group, type, level, priority, contraindications, substitute_for, prehab_target)
values
  ('Жим штанги лежа','chest','{compound,push,upper}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Жим штанги лежа на наклонной скамье','chest','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Жим гантелей лежа','chest','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Жим гантелей лежа на наклонной скамье','chest','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Жим сидя в тренажере','chest','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Разведение гантелей лежа','chest','{isolation,push,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Бабочка','chest','{isolation,push,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Сведение рук в кроссовере','chest','{isolation,push,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Тяга верхнего блока','back','{compound,pull,upper}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Тяга верхнего блока обратным хватом','back','{compound,pull,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Тяга горизонтального блока к груди','back','{compound,pull,upper}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Гребная тяга в тренажере','back','{compound,pull,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Хаммер вертикальный','back','{compound,pull,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Пулловер','back','{isolation,pull,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Тяга штанги в наклоне','back','{compound,pull,upper}','{beginner,intermediate,advanced}','main','{lower_back}','{}',NULL),
  ('Тяга гантелей в наклоне','back','{compound,pull,upper}','{beginner,intermediate,advanced}','secondary','{lower_back}','{}',NULL),
  ('Шраги','back','{isolation,pull,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Подтягивания в гравитроне','back','{compound,pull,upper}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Гиперэкстензия','back','{accessory,lower}','{beginner,intermediate,advanced}','accessory','{lower_back}','{}',NULL),
  ('Тяга Т-образного грифа','back','{compound,pull,upper}','{beginner,intermediate,advanced}','main','{lower_back}','{}',NULL),
  ('Приседания со штангой','quads','{compound,lower,squat}','{beginner,intermediate,advanced}','main','{lower_back,knee}','{}',NULL),
  ('Приседания со штангой в смите','quads','{compound,lower,squat}','{beginner,intermediate,advanced}','secondary','{lower_back,knee}','{}',NULL),
  ('Разгибание голени','quads','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{knee}','{}',NULL),
  ('Выпады с гантелями','quads','{compound,lower}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Жим платформы ногами','quads','{compound,lower}','{beginner,intermediate,advanced}','main','{knee}','{}',NULL),
  ('Жим платформы паралельный','quads','{compound,lower}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Гакк приседания','quads','{compound,lower,squat}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Приседания гоблет','quads','{compound,lower,squat}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Сгибание голени','hamstrings','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Сгибание голени сидя','hamstrings','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Приседания со штангой в смите','hamstrings','{compound,lower,squat}','{beginner,intermediate,advanced}','secondary','{lower_back,knee}','{}',NULL),
  ('Жим ногами высокая пост. стопы','hamstrings','{compound,lower}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Сгибание голени в кроссовере','hamstrings','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Мертвая тяга','hamstrings','{compound,lower,hinge}','{beginner,intermediate,advanced}','main','{lower_back}','{}',NULL),
  ('Приседание плие','glutes','{compound,lower}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Румынская тяга штанги','glutes','{compound,lower,hinge}','{beginner,intermediate,advanced}','secondary','{lower_back}','{}',NULL),
  ('Ягодичный мостик','glutes','{compound,lower}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Болгарские приседания','glutes','{compound,lower}','{beginner,intermediate,advanced}','secondary','{knee}','{}',NULL),
  ('Разгибание бедра в кроссовере','glutes','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Приведение бедра','glutes','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Отведение бедра','glutes','{isolation,lower}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Гиперэкстензия на ягодицы','glutes','{accessory,lower}','{beginner,intermediate,advanced}','accessory','{lower_back}','{}',NULL),
  ('Жим гантелей сидя','shoulders_front','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{shoulder}','{}',NULL),
  ('Жим арнольда','shoulders_front','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{shoulder}','{}',NULL),
  ('Армейский жим стоя','shoulders_front','{compound,push,upper}','{beginner,intermediate,advanced}','main','{shoulder}','{}',NULL),
  ('Жим штанги сидя в смите','shoulders_front','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{shoulder}','{}',NULL),
  ('Махи вперед с гантелями','shoulders_front','{isolation,push,upper}','{beginner,intermediate,advanced}','accessory','{shoulder}','{}',NULL),
  ('Жим от плеч в тренажере','shoulders_front','{compound,push,upper}','{beginner,intermediate,advanced}','secondary','{shoulder}','{}',NULL),
  ('Махи с гантелями сидя','shoulders_side','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Махи с гантелями стоя','shoulders_side','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Протяжка со штангой','shoulders_side','{compound,upper}','{beginner,intermediate,advanced}','secondary','{shoulder}','{}',NULL),
  ('Махи в кроссовере','shoulders_side','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Отведение плеча в кроссовере','shoulders_rear','{isolation,upper,pull}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Отведение плеча в бабочке','shoulders_rear','{isolation,upper,pull}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Отведение плеча на скамье с гантелями','shoulders_rear','{isolation,upper,pull}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Cгибание предплечья Larry Scott','biceps','{isolation,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Сгибание предплечья со штангой','biceps','{compound,upper}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Сгибание предплечья с гантелями','biceps','{isolation,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Сгибание предплечья в кроссовере','biceps','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Боковая тяга тросса на бицепс','biceps','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Фрунцузский жим с гантелями','triceps','{isolation,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Фрунцузский жим с штангой','triceps','{isolation,upper}','{beginner,intermediate,advanced}','secondary','{}','{}',NULL),
  ('Жим гантели из-за головы','triceps','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Разгибание предплечья в кроссовере','triceps','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Разгибание предплечья из-за голов. в кроссоверы','triceps','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL),
  ('Жим лежа штанги узким хватом','triceps','{compound,push,upper}','{beginner,intermediate,advanced}','main','{}','{}',NULL),
  ('Поочередное разгибание предплечья в кроссовере','triceps','{isolation,upper}','{beginner,intermediate,advanced}','accessory','{}','{}',NULL);
